name: Check Markdown links

on: push

jobs:
  check-md-links:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/dcomp
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check Markdown links
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          config_file: .github/config/linkspector.yml
          fail_on_error: true
